- name: set environment variables for postgres
  hosts: localhost
  gather_facts: true
  tasks:
    - name: Set POSTGRES_USER environment variable
      ansible.builtin.shell: echo 'export POSTGRES_USER="{{ POSTGRES_USER }}"' >> /etc/environment

    - name: Set POSTGRES_PASSWORD environment variable
      ansible.builtin.shell: echo 'export POSTGRES_PASSWORD="{{ POSTGRES_PASSWORD }}"' >> /etc/environment

    - name: Set POSTGRES_DB environment variable
      ansible.builtin.shell: echo 'export POSTGRES_DB="{{ POSTGRES_DB }}"' >> /etc/environment

    - name: display id
      ansible.builtin.debug:
        var: ansible_user_id

    - name: Check for subdirectories in data
      ansible.builtin.find:
        paths: "/data"
        file_type: directory
      register: subdirs

    - name: display subdirs
      ansible.builtin.debug:
        var: subdirs

    - name: Set POSTGRES_DATA environment variable (no linked storage)
      ansible.builtin.shell: echo 'export POSTGRES_DATA="/data/postgres"' >> /etc/environment
      when: subdirs.matched == 1

    - name: Set POSTGRES_DATA environment variable (linked storage)
      ansible.builtin.shell: echo 'export POSTGRES_DATA="{{ subdirs.files[0].path }}/postgres"' >> /etc/environment
      when: subdirs.matched != 1

    - name: make sure the postgres data directory exists
      ansible.builtin.file:
      path: "{{ POSTGRES_DATA }}"
      state: directory
