- name: set environment variables for postgres
  hosts: localhost
  gather_facts: true
  tasks:
    - name: Set POSTGRES_USER environment variable
      ansible.builtin.shell: echo 'export POSTGRES_USER="{{ POSTGRES_USER }}"' >> /etc/environment

    - name: Set POSTGRES_PASSWORD environment variable
      ansible.builtin.shell: echo 'export POSTGRES_PASSWORD="{{ POSTGRES_PASSWORD }}"' >> /etc/environment

    - name: Set POSTGRES_DB environment variable
      ansible.builtin.shell: echo 'export POSTGRES_DB="{{ POSTGRES_DB }}"' >> /etc/environment

    - name: Check for subdirectories in data directory
      ansible.builtin.find:
        paths: "/data"
        file_type: directory
      register: subdirs

    - name: Set POSTGRES_DATA environment variable (no linked storage)
      set_fact:
        POSTGRES_DATA: "/data/postgres"
      when: subdirs.matched == 1

    - name: Set POSTGRES_DATA variable (linked storage)
      set_fact:
        POSTGRES_DATA: "{{ subdirs.files[0].path }}/postgres"
      when: subdirs.matched != 1

    - name: Set POSTGRES_DATA environment variable
      ansible.builtin.shell: echo 'export POSTGRES_DATA="{{ POSTGRES_DATA }}"' >> /etc/environment

    - name: make sure the postgres data directory exists
      ansible.builtin.file:
        path: "{{ POSTGRES_DATA }}"
        state: directory
