- name: set environment variables for postgres
  hosts: localhost

  tasks:
    - name: Set POSTGRES_USER environment variable
      ansible.builtin.shell: echo 'export POSTGRES_USER="{{ POSTGRES_USER }}"' >> /etc/environment

    - name: Set POSTGRES_PASSWORD environment variable
      ansible.builtin.shell: echo 'export POSTGRES_PASSWORD="{{ POSTGRES_PASSWORD }}"' >> /etc/environment

    - name: Set POSTGRES_DB environment variable
      ansible.builtin.shell: echo 'export POSTGRES_DB="{{ POSTGRES_DB }}"' >> /etc/environment