- name: set environment variables & run docker-compose up -d
  hosts: localhost

  vars:
    postgres_dir: /home/tscheidel/postgres
    repo_url: "https://github.com/sche34/change_postgres.git"

  tasks:
    - name: Creates directory
      ansible.builtin.file:
        path: "{{ postgres_dir }}"
        state: directory

    - name: Clone the Git repository into the shared project directory
      git:
        repo: "{{ repo_url }}"
        dest: "{{ project_dir }}"
        version: main
        force: yes
        accept_hostkey: yes

    - name: Create a file
      ansible.builtin.file:
        path: "{{ postgres_dir }}/.env"
        state: touch

    - name: Write postgres user to .env file
      ansible.builtin.lineinfile:
        path: "{{ postgres_dir }}/.env"
        line: 'POSTGRES_USER="{{ POSTGRES_USER }}"'

    - name: Write postgres password to .env file
      ansible.builtin.lineinfile:
        path: "{{ postgres_dir }}/.env"
        line: 'POSTGRES_PASSWORD="{{ POSTGRES_PASSWORD }}"'

    - name: Write postgres db to .env file
      ansible.builtin.lineinfile:
        path: "{{ postgres_dir }}/.env"
        line: 'POSTGRES_DB="{{ POSTGRES_DB }}"'
