- name: set environment variables for postgres
  hosts: localhost

  tasks:
    - name: Set POSTGRES_USER environment variable
      ansible.builtin.shell: echo 'export POSTGRES_USER="{{ POSTGRES_USER }}"' >> /etc/environment

    - name: Set POSTGRES_PASSWORD environment variable
      ansible.builtin.shell: echo 'export POSTGRES_PASSWORD="{{ POSTGRES_PASSWORD }}"' >> /etc/environment

    - name: Set POSTGRES_DB environment variable
      ansible.builtin.shell: echo 'export POSTGRES_DB="{{ POSTGRES_DB }}"' >> /etc/environment

    - name: Check for subdirectories in data
      ansible.builtin.find:
      paths: /home/{{ ansible_user }}/data
      file_type: directory
      register: subdirs

    - name: Ensure postgres directory exists if no other subdirectories, which means that there is not linked storage
      ansible.builtin.file:
      path: /home/{{ ansible_user }}/postgres
      state: directory
      when: subdirs.matched == 1

    - name: Set POSTGRES_DATA environment variable
      ansible.builtin.shell: echo 'export POSTGRES_DATA="/home/{{ ansible_user }}/postgres"' >> /etc/environment
      when: subdirs.matched == 1

    - name: Set POSTGRES_DATA environment variable
      ansible.builtin.shell: echo 'export POSTGRES_DATA="{{ item.path }}"' >> /etc/environment
      with_items: "{{ subdirs.files }}"
      when: item.path != '/home/{{ ansible_user }}/data/datasets'