- name: set environment variables for postgres
  hosts: localhost
  gather_facts: true

  tasks:
    - name: Set POSTGRES_USER environment variable
      ansible.builtin.shell: echo 'export POSTGRES_USER="{{ POSTGRES_USER }}"' >> /etc/environment

    - name: Set POSTGRES_PASSWORD environment variable
      ansible.builtin.shell: echo 'export POSTGRES_PASSWORD="{{ POSTGRES_PASSWORD }}"' >> /etc/environment

    - name: Set POSTGRES_DB environment variable
      ansible.builtin.shell: echo 'export POSTGRES_DB="{{ POSTGRES_DB }}"' >> /etc/environment

    - name: display id
      ansible.builtin.debug:
        var: ansible_user_id

    - name: Check for subdirectories in data
      ansible.builtin.find:
        paths: /home/{{ ansible_user_id }}/data
        file_type: directory
      register: subdirs

    - name: Ensure postgres directory exists if no other subdirectories, which means that there is not linked storage
      ansible.builtin.file:
        path: /home/{{ ansible_user_id }}/postgres
        state: directory
      when: subdirs.matched == 1

    - name: display subdirs
      ansible.builtin.debug:
        var: subdirs

    - name: Set POSTGRES_DATA environment variable
      ansible.builtin.shell: |
        if [ {{ subdirs.matched }} -eq 1 ]; then
          echo 'export POSTGRES_DATA="/home/{{ ansible_user_id }}/postgres"' >> /etc/environment
        else
          for item in {{ subdirs.files }}; do
            if [ "$item.path" != "/home/{{ ansible_user_id }}/data/datasets" ]; then
              echo 'export POSTGRES_DATA="$item.path"' >> /etc/environment
            fi
          done
        fi